# extra generation configs will be loaded from the model config during runtime
strategy: ar

# parallel decoding proposed in https://arxiv.org/abs/2505.22618
threshold: null # all tokens whose confidence is above this threshold will be fixed

alg: "maskgit_plus"
gen_length: null
block_length: null
num_transfer_tokens: 1
temperature: 0.0
top_p: null
top_k: null

# whether to stop generation when meets the EOS token
stop_until_eos: false

# whether to use debiasing trivial tokens, see https://arxiv.org/pdf/2508.13021
# to enable debiasing, {model-family.lower()}_corpus.json should be placed in the src/third_party/ directory
# e.g., llada_corpus.json for LLaDA
debias: false

output_probs: false