# extra generation configs will be loaded from the model config during runtime
strategy: vanilla

# parallel decoding proposed in https://arxiv.org/abs/2505.22618, only one of these two can be specified
threshold: null # all tokens whose confidence is above this threshold will be fixed
factor: null # factor-based parallel decoding factor

alg: "maskgit_plus"
gen_length: null
block_length: null
num_transfer_tokens: 1
temperature: 0.0
top_p: null
top_k: null

# The standard deviation of the Gaussian kernel used in decoding with certainty prior, see https://arxiv.org/abs/2509.23094.
sigma: null 

# whether to stop generation when meets the EOS token
stop_until_eos: false

output_probs: false